project:
  type: website

website:
  title: "huntley.link"
  image: "quarto.png"
  favicon: "longlink3.png"
  page-navigation: true
  navbar:
    background: light
    logo: longlink3.png
    title: huntley.link
    collapse-below: lg
    left:
      - text: About
        href: about.qmd
      - blog.qmd
      - text: Books
        menu:
          - text: Epistles
            href: books/epistles/index.qmd
  page-footer:
    left: |
      Copyright © 2022 Stephen E. Huntley
    center: |
      Created with
      [![](quarto.png){width=85px}](https://quarto.org/)
  sidebar:
    - id: blog
      contents:
        - text: Blog Archive
          href: blog.qmd
        - section: y 2022
          contents:
            - section: Feb
              contents:
                - books/epistles/3_references.qmd
                - books/epistles/2_summary.qmd
        - section: y 2019
          contents:
            - section: Jan
              contents:
                - books/epistles/1_intro.qmd
                - books/epistles/index.qmd
format:
  html:
    toc: true
    theme: 
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css