project:
  type: website
website:
  title: huntley.link
  site-url: https://stephen.huntley.link
  description: Personal archive, notes and works in progress.
  image: /img/opengraph.png
  favicon: /img/HLicon.png
  twitter-card:
    image: /img/opengraph.png
  open-graph:
    image: /img/opengraph.png
  repo-url: https://github.com/huntley-link/huntley-link.github.io
  repo-branch: public
  repo-actions:
    - source
  navbar:
    logo: /img/HLicon.png
    right:
      - icon: rss
        href: blog.xml
    left:
      - href: index.qmd
        text: Home
      - text: Blog
        href: blog.qmd
      - text: Books
        menu:
          - text: Epistles
            href: books/epistles/index.qmd
          - text: Log
            href: books/log/index.qmd
          - text: Archive
            href: books/archive/index.qmd
  page-footer:
    left: |
      Copyright © 2023 Stephen E. Huntley
    center: |
      Created with
      [![](/img/quarto.png){width=85px}](https://quarto.org/)
format:
  html:
    theme: cosmo
    css: styles.css
    embed-resources: false
metadata-files:
  - _metadata.yml
