project:
  type: website

website:
  title: "huntley.link"
  image: "quarto.png"
  favicon: "longlink3.png"
  page-navigation: true
  navbar:
    background: light
    logo: longlink3.png
    title: huntley.link
    collapse-below: lg
    left:
      - about.qmd
      - blog.qmd
      - text: Books
        menu:
          - text: Epistles
            href: books/epistles/index.qmd
  page-footer:
    left: |
      Copyright © 2022 Stephen E. Huntley
    center: |
      Created with
      [![](quarto.png){width=85px}](https://quarto.org/)
format:
  html:
    toc: true
    theme: 
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css