project:
  type: website
website:
  title: huntley.link
  image: quarto.png
  favicon: longlink3.png
  page-navigation: true
  navbar:
    background: light
    logo: longlink3.png
    title: huntley.link
    collapse-below: lg
    left:
      - text: About
        href: about.qmd
      - blog.qmd
      - text: Books
        menu:
          - text: Epistles
            href: books/epistles/index.qmd
  page-footer:
    left: |
      Copyright © 2022 Stephen E. Huntley
    center: |
      Created with
      [![](quarto.png){width=85px}](https://quarto.org/)
  sidebar:
    - id: blog
      contents:
        - text: Blog Archive
          href: blog.qmd
        - section: 2022 (2)
          contents:
            - section: Feb (2)
              contents:
                - books/epistles/3_references.qmd
                - books/epistles/2_summary.qmd
        - section: 2019 (2)
          contents:
            - section: Jan (2)
              contents:
                - books/epistles/index.qmd
                - books/epistles/1_intro.qmd
format:
  html:
    toc: true
    theme:
      light:
        - cosmo
        - theme.scss
    code-copy: true
    code-overflow: wrap
    css: styles.css
