project:
  type: book
book:
  title: "Archive"
  author: "Stephen Huntley"
  cover-image: hypostatk0.png
  date: "3/26/2022"
  favicon: "longlink3.png"
  number-depth: 0
  repo-url: "https://github.com/huntley-link/huntley-link.github.io/books/archive"
  repo-branch: public
  repo-actions: [source]
  navbar:
    background: light
    logo: longlink3.png
    title: "Archive"
    collapse-below: lg
    left:
      - text: "Site Home"
        href: "http://localhost:8080/doc/ckout/_site/index.html"
  chapters:
    - index.qmd
bibliography: references.bib
format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    number-sections: false
  pdf:
    documentclass: scrreprt
