project:
  type: book
  output-dir: "../../_site/books/archive"
book:
  title: "Archive"
  author: "Stephen Huntley"
  site-url: "https://stephen.huntley.link/books/archive"
  cover-image: "img/archive-cover.png"
  date: "4/21/2023"
  favicon: "img/hypostatk0.png"
  repo-subdir: "books/archive"
  navbar:
    title: "Archive"
  chapters:
    - index.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    css: bookstyles.css
    number-sections: false
    embed-resources: false
  pdf:
    number-sections: false
metadata-files:
  - "../_books.yml"
